# Tap
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'

# Div
brew 'coreutils'
brew 'bash-completion'
brew 'git'
brew 'bash-git-prompt'
brew 'z'
brew 'speedtest-cli'
brew 'gh'
brew 'cask'
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'maven'
brew 'maven-completion'
brew 'cheat'
brew 'vim'
brew 'wget'
brew 'helm'
brew 'python'
brew 'brew-pip'
brew 'node'
brew 'npm'
brew 'exa'
brew 'kubeseal'
brew 'thefuck'
brew 'fish'
brew 'starship'
brew 'kubernetes-cli'
brew 'mkdocs'
brew 'mvndaemon/homebrew-mvnd/mvnd'

# Casks
cask 'docker'
cask 'iterm2'
cask 'keystore-explorer'
cask 'font-jetbrains-mono'
cask 'font-jetbrains-mono-nerd-font'
cask 'visual-studio-code'

# Temurin Java
cask 'temurin'
cask 'temurin17'
cask 'temurin8'
cask 'temurin11'
